{
 "title": "Espresso Node Monitoring Public",
 "tags": [
  "consensus",
  "monitoring"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "chain_env", "label": "Chain Env", "query": { "query": "label_values(chain_env)" } }
  ]
 },
 "panels": [
  { "title": "Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected Peers on the Libp2p network",
   "type": "stat",
   "description": "The number of connected peers on the Libp2p network. This should be nonzero.",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consensus_libp2p_num_connected_peers{chain_env=\"testnet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last Synced Block Height",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "consensus_last_synced_block_height{chain_env=\"$chain_env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus Current View",
   "type": "timeseries",
   "description": "should be incrementing once every 1-2 seconds. In rare cases it is acceptable for this metric to remain static for up to 1 minute. If not increasing, it may mean the network has lost liveness, or your node has fallen out of sync with the network.",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "consensus_current_view{chain_env=\"$chain_env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus Last Decided View",
   "type": "timeseries",
   "description": "should be increasing mostly in tandem with consensus_current_view. If current_view is increasing but last_decided_view is not, it indicates a network-wide problem with consensus state, or a recurring problem with builders or proposer",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 9 },
   "targets": [
    {
     "expr": "consensus_last_decided_view{chain_env=\"testnet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Timeout Rate as Leader",
   "type": "timeseries",
   "description": "The number of slots (views) this leader has failed to propose a block for. If this is increasing frequently, there is potentially an issue with your node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "consensus_number_of_timeouts_as_leader{chain_env=\"$chain_env\"}",
     "legendFormat": "{{instance}} - Timeouts as Leader"
    }
   ]
  },
  {
   "title": "Outstanding Transactions",
   "type": "timeseries",
   "description": "smaller is better, and this metric should not show any trend over time. If it is especially large (relative to volume) or increasing over a long period of time, it may indicate that your node is not garbage collecting the public mempool properly.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "consensus_outstanding_transactions{chain_env=\"testnet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Node Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Node Identity",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "consensus_node_identity_general{chain_env=\"$chain_env\"}"
    }
   ]
  },
  {
   "title": "Version Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "consensus_version{chain_env=\"$chain_env\"}"
    }
   ]
  }
 ]
}